apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: spark
    app.kubernetes.io/name: spark
  name: spark-master
  namespace: spark-cluster
spec:
  ports:
  - name: cluster
    port: 7077
    protocol: TCP
    targetPort: cluster
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: spark
    app.kubernetes.io/name: spark
  sessionAffinity: None
  type: ClusterIP
  externalIPs:
    - 127.0.0.1