kind: Namespace
apiVersion: v1
metadata:
  name: spark-cluster
  labels:
    name: spark-cluster
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/component: master
    app.kubernetes.io/name: spark
  name: spark-master
  namespace: spark-cluster
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: master
      app.kubernetes.io/name: spark
  serviceName: spark
  template:
    metadata:
      labels:
        app.kubernetes.io/component: master
        app.kubernetes.io/instance: spark
        app.kubernetes.io/name: spark
    spec:
      containers:
      - env:
        - name: SPARK_MODE
          value: master
        - name: SPARK_DAEMON_MEMORY
        - name: SPARK_MASTER_PORT
          value: "7077"
        - name: SPARK_MASTER_WEBUI_PORT
          value: "8080"
        image: docker.io/bitnami/spark:2.4.5-debian-10-r111
        imagePullPolicy: IfNotPresent
        name: spark-master
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 7077
          name: cluster
          protocol: TCP
        resources: {}
      restartPolicy: Always
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate